services:
  mongodb: 
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: juano
      MONGO_INITDB_ROOT_PASSWORD: "21950524"
    volumes:
      - /data/db
    container_name: mongodb
    networks:
      - localpc

networks:
  localpc:
    driver: bridge
    

    